name: "Client"

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: "Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install"
        run: npm ci

      - name: "Type check"
        run: npm run type-check

      - name: "Lint"
        run: npm run lint

  deploy-dev:
    name: "Deploy (dev)"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint]
    defaults:
      run:
        working-directory: ./client/
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install"
        run: npm ci

      - name: "Build"
        run: npm run build:dev

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: dev
          workingDirectory: ./client/

  deploy-prod:
    name: "Deploy (prod)"
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: [lint]
    defaults:
      run:
        working-directory: ./client/
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install"
        run: npm ci

      - name: "Build"
        run: npm run build:prod

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: prod
          workingDirectory: ./client/
